/**
 * General Knowledge Deck (100 Cards)
 * Curated high-interest questions across Science, History, Arts, Literature, and Modern Tech.
 * Pre-seeded with a realistic spaced repetition schedule for immediate learning and calendar forecast.
 */

import { getDateString, addDays } from './srs.js';

export function getGeneralKnowledgeData() {
  const today = getDateString();
  const now = new Date().toISOString();

  const gkGroups = [
    {
      id: 'grp_gk',
      parentId: null,
      name: "General Knowledge",
      type: 'class',
      color: '#c05638',
      icon: 'globe',
      createdAt: now
    },
    {
      id: 'grp_gk_u1',
      parentId: 'grp_gk',
      name: "Unit 1: Science & Nature",
      type: 'unit',
      color: '#2d6a4f',
      icon: 'microscope',
      createdAt: now
    },
    {
      id: 'grp_gk_u2',
      parentId: 'grp_gk',
      name: "Unit 2: World History & Geography",
      type: 'unit',
      color: '#3d6884',
      icon: 'compass',
      createdAt: now
    },
    {
      id: 'grp_gk_u3',
      parentId: 'grp_gk',
      name: "Unit 3: Arts, Literature & Philosophy",
      type: 'unit',
      color: '#7c3aed',
      icon: 'palette',
      createdAt: now
    },
    {
      id: 'grp_gk_u4',
      parentId: 'grp_gk',
      name: "Unit 4: Space, Tech & Modern World",
      type: 'unit',
      color: '#b87320',
      icon: 'atom',
      createdAt: now
    }
  ];

  const gkCards = [
    {
      id: 'card_gk_001',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What organelle is famously known as the 'powerhouse of the cell'?",
      back: "Mitochondria (produces energy in the form of ATP via cellular respiration).",
      hint: "Generates adenosine triphosphate (ATP)",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "biology", "cells"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_002',
      groupId: 'grp_gk_u1',
      type: 'reversible',
      front: "What is the chemical symbol for Gold?",
      back: "Au (from Latin 'Aurum')",
      hint: "Derived from the Latin word meaning shining dawn",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "chemistry", "elements"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_003',
      groupId: 'grp_gk_u1',
      type: 'cloze',
      front: "Speed of light in vacuum",
      back: "Denoted by the constant 'c' in Einstein's E = mc\u00b2 equation.",
      hint: '',
      clozeText: "The speed of light in a vacuum is approximately {{c1::300,000}} km/s (or {{c1::3 x 10^8}} m/s).",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "physics"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_004',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What is the hardest known natural mineral on Earth?",
      back: "Diamond (a carbon allotrope ranking 10 on the Mohs hardness scale).",
      hint: "Composed of pure carbon arranged in a crystal lattice",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "geology"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_005',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What gas do green plants absorb from the air to perform photosynthesis?",
      back: "Carbon dioxide (CO\u2082).",
      hint: "They release oxygen as a byproduct",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "botany", "biology"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_006',
      groupId: 'grp_gk_u1',
      type: 'reversible',
      front: "What is the closest star to planet Earth?",
      back: "The Sun (at an average distance of ~149.6 million km / 1 AU).",
      hint: "Center of our solar system",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "astronomy"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_007',
      groupId: 'grp_gk_u1',
      type: 'reversible',
      front: "What is the chemical formula for ordinary table salt?",
      back: "NaCl (Sodium Chloride).",
      hint: "Formed from sodium cations and chloride anions",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "chemistry"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_008',
      groupId: 'grp_gk_u1',
      type: 'cloze',
      front: "Newton's fundamental laws",
      back: "Laid the foundation for classical Newtonian mechanics.",
      hint: '',
      clozeText: "Sir Isaac Newton formulated the three laws of {{c1::motion}} and the law of universal {{c2::gravitation}} in his 1687 work Principia.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "physics", "history"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_009',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "Why does Mars appear reddish in color?",
      back: "Iron oxide (rust) covering much of its rocky surface.",
      hint: "Think of oxidized iron",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "space"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_010',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What tough polymer forms the cell walls of fungi and the exoskeletons of arthropods?",
      back: "Chitin.",
      hint: "A long-chain polymer of N-acetylglucosamine",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "biology"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_011',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What is the most abundant gas in Earth's atmosphere by volume?",
      back: "Nitrogen (N\u2082), accounting for approximately 78% of dry air.",
      hint: "Oxygen is second at ~21%",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "atmosphere", "earth"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_012',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "Which ABO/Rh blood type is considered the universal red blood cell donor?",
      back: "O-negative (O-).",
      hint: "Lacks A, B, and Rh antigens on erythrocytes",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "medicine", "biology"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_013',
      groupId: 'grp_gk_u1',
      type: 'cloze',
      front: "Density of water",
      back: "This anomalous expansion causes ice to float on liquid water, protecting aquatic ecosystems.",
      hint: '',
      clozeText: "Liquid water reaches its maximum density at {{c1::4}} degrees Celsius (39.2\u00b0F).",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "physics", "chemistry"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_014',
      groupId: 'grp_gk_u1',
      type: 'reversible',
      front: "What is the SI unit of electrical resistance?",
      back: "Ohm (symbol: \u03a9).",
      hint: "Named after physicist Georg Simon Ohm",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "physics"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_015',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What is the term for the evaporation of water vapor through the stomata of plant leaves?",
      back: "Transpiration.",
      hint: "Drives the capillary pull of water up through xylem vessels",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "botany"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_016',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "How many total chromosomes are present in a normal human diploid somatic cell?",
      back: "46 chromosomes (23 homologous pairs).",
      hint: "Gametes (sperm and egg) have 23 haploid chromosomes",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "genetics", "biology"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_017',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "Which subatomic particle carries a negative electric charge?",
      back: "Electron (discovered by J.J. Thomson in 1897).",
      hint: "Orbits the atomic nucleus composed of protons and neutrons",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "physics", "chemistry"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_018',
      groupId: 'grp_gk_u1',
      type: 'cloze',
      front: "Periodic table ordering",
      back: "Arranged originally by Dmitri Mendeleev according to atomic mass.",
      hint: '',
      clozeText: "Elements in the modern periodic table are arranged in order of increasing {{c1::atomic number}}, which equals the number of {{c2::protons}} in the atomic nucleus.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "chemistry"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_019',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What chemical bond type involves the sharing of electron pairs between atoms?",
      back: "Covalent bond.",
      hint: "Contrasts with ionic bonds where electrons are transferred",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "chemistry"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_020',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "Which mammal is the only one capable of true, powered flight?",
      back: "The Bat (order Chiroptera).",
      hint: "Flying squirrels only glide",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "zoology"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_021',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What is molten rock called while it is still beneath the Earth's surface?",
      back: "Magma (it is called lava once it erupts onto the surface).",
      hint: "Formed in the crust and mantle",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "geology"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_022',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "Which endocrine gland produces the hormones insulin and glucagon?",
      back: "The Pancreas (specifically the Islets of Langerhans).",
      hint: "Regulates blood glucose levels",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "anatomy", "medicine"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_023',
      groupId: 'grp_gk_u1',
      type: 'cloze',
      front: "Sound wave propagation",
      back: "Particles oscillate parallel to the direction of wave travel.",
      hint: '',
      clozeText: "Sound waves are {{c1::longitudinal}} mechanical waves that require a physical {{c2::medium}} to propagate, meaning they cannot travel through a vacuum.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "physics"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_024',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What is the pH value of pure neutral water at 25\u00b0C?",
      back: "pH 7.0 (where hydrogen ion concentration equals hydroxide ion concentration: 10\u207b\u2077 M).",
      hint: "Values below 7 are acidic; above 7 are basic/alkaline",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "chemistry"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_025',
      groupId: 'grp_gk_u1',
      type: 'basic',
      front: "What is the primary green pigment in plant chloroplasts responsible for capturing sunlight?",
      back: "Chlorophyll (primarily chlorophyll a and b).",
      hint: "Contains a central magnesium ion in a porphyrin ring",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "botany"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_026',
      groupId: 'grp_gk_u2',
      type: 'reversible',
      front: "What is the capital city of Australia?",
      back: "Canberra (chosen as a compromise between Sydney and Melbourne in 1908).",
      hint: "Located in the Australian Capital Territory (ACT)",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "capitals"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_027',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "In what year did World War II conclude with the surrender of Axis forces?",
      back: "1945 (VE Day on May 8, VJ Day on August 15 / Sept 2).",
      hint: "The year the United Nations was founded",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "ww2"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_028',
      groupId: 'grp_gk_u2',
      type: 'cloze',
      front: "Founding topography of Rome",
      back: "Including the Palatine, Capitoline, Quirinal, Viminal, Esquiline, Caelian, and Aventine.",
      hint: '',
      clozeText: "Ancient {{c1::Rome}} was famously founded along the Tiber River upon {{c2::seven}} hills.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "rome"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_029',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Which African river is traditionally recognized as the longest river on Earth?",
      back: "The Nile River (~6,650 km / 4,132 miles).",
      hint: "Flows northward into the Mediterranean Sea",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "rivers"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_030',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Which pre-Columbian civilization constructed the mountain citadel Machu Picchu?",
      back: "The Inca Empire (built around 1450 CE under Emperor Pachacuti).",
      hint: "Located in modern-day Peru above the Sacred Valley",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "americas"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_031',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "What narrow waterway connects the Atlantic Ocean to the Mediterranean Sea?",
      back: "The Strait of Gibraltar.",
      hint: "Separates southern Spain from northern Morocco",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "straits"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_032',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Who was the first Emperor of a unified China and creator of the Terracotta Army?",
      back: "Qin Shi Huang (259\u2013210 BCE, founder of the Qin dynasty).",
      hint: "Standardized weights, measures, Chinese script, and connected early defensive walls",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "china"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_033',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "What is the largest and deepest of Earth's oceanic divisions?",
      back: "The Pacific Ocean (covering more than 30% of the Earth's surface area).",
      hint: "Named by Ferdinand Magellan for its calm waters ('Mar Pac\u00edfico')",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "oceans"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_034',
      groupId: 'grp_gk_u2',
      type: 'cloze',
      front: "The Great Charter",
      back: "Established the principle that everyone, even the monarch, is subject to the rule of law.",
      hint: '',
      clozeText: "The Magna Carta was sealed at Runnymede in the year {{c1::1215}} by King {{c2::John}} of England.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "law"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_035',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "What is the highest mountain peak on Earth above sea level?",
      back: "Mount Everest (8,848.86 m / 29,031.7 ft; known as Sagarmatha or Chomolungma).",
      hint: "Located in the Mahalangur Himal sub-range of the Himalayas",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "mountains"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_036',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Which country contains more natural lakes than the rest of the world combined?",
      back: "Canada (estimated over 879,000 lakes, largely glacial).",
      hint: "Second largest country by total land area",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "countries"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_037',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "What was the capital of the Eastern Roman (Byzantine) Empire before its fall in 1453?",
      back: "Constantinople (modern-day Istanbul, Turkey).",
      hint: "Founded by Constantine the Great on the site of ancient Byzantium",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "byzantine"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_038',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "What is the deepest known oceanic depression on Earth?",
      back: "The Mariana Trench (Challenger Deep, reaching ~11,000 meters / 36,000 ft deep).",
      hint: "Located in the western Pacific Ocean",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "oceans"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_039',
      groupId: 'grp_gk_u2',
      type: 'reversible',
      front: "What is the capital city of Japan?",
      back: "Tokyo (formerly known as Edo until 1868).",
      hint: "Located on the eastern coast of Honshu",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "capitals"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_040',
      groupId: 'grp_gk_u2',
      type: 'cloze',
      front: "Fall of the Iron Curtain landmark",
      back: "Symbolized the collapse of the Eastern Bloc and the imminent end of the Cold War.",
      hint: '',
      clozeText: "The Berlin Wall fell on November 9, {{c1::1989}}, paving the way for the reunification of {{c2::Germany}} in 1990.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "cold-war"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_041',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "What is the largest non-polar (hot) desert in the world?",
      back: "The Sahara Desert (~9.2 million square kilometers in North Africa).",
      hint: "Antarctica and the Arctic are larger polar deserts",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "deserts"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_042',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Who served as the first President of the United States under the Constitution?",
      back: "George Washington (served 1789\u20131797).",
      hint: "Commander of the Continental Army during the Revolutionary War",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "usa"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_043',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "What is the smallest sovereign state in the world by both area and population?",
      back: "Vatican City State (~0.49 sq km / 121 acres).",
      hint: "An enclave entirely surrounded by the city of Rome, Italy",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "countries"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_044',
      groupId: 'grp_gk_u2',
      type: 'cloze',
      front: "Origins of the Renaissance",
      back: "Fueled by humanist scholarship, classical antiquity revival, and patronage from families like the Medici.",
      hint: '',
      clozeText: "The European Renaissance began in the 14th century in the country of {{c1::Italy}}, particularly in the wealthy city of {{c2::Florence}}.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "renaissance"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_045',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Which Genoese navigator made four voyages across the Atlantic sponsored by Catholic Monarchs of Spain starting in 1492?",
      back: "Christopher Columbus.",
      hint: "Sailed aboard the Ni\u00f1a, Pinta, and Santa Mar\u00eda",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "exploration"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_046',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Which Middle Eastern nation was known internationally as Persia until 1935?",
      back: "Iran (officially the Islamic Republic of Iran).",
      hint: "Requested the international community to use its native name Iran under Reza Shah",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "geography"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_047',
      groupId: 'grp_gk_u2',
      type: 'reversible',
      front: "What is the federal capital city of Canada?",
      back: "Ottawa (located in Ontario on the south bank of the Ottawa River).",
      hint: "Chosen by Queen Victoria in 1857",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "capitals"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_048',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Which artificial waterway opened in 1869 connects the Mediterranean Sea to the Red Sea?",
      back: "The Suez Canal in Egypt.",
      hint: "Enables maritime transit between Europe and Asia without circumnavigating Africa",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "history"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_049',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "Who served as Prime Minister of the United Kingdom through most of the Second World War (1940\u20131945)?",
      back: "Winston Churchill.",
      hint: "Famous for his 'We shall fight on the beaches' and 'Blood, toil, tears and sweat' speeches",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["history", "uk"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_050',
      groupId: 'grp_gk_u2',
      type: 'basic',
      front: "What is the largest non-continental island in the world?",
      back: "Greenland (Kalaallit Nunaat, ~2.16 million sq km, an autonomous territory of Denmark).",
      hint: "Australia is classified as a continent rather than an island",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["geography", "islands"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_051',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Who painted the Renaissance masterpieces 'The Mona Lisa' and 'The Last Supper'?",
      back: "Leonardo da Vinci (1452\u20131519).",
      hint: "Italian polymath of the High Renaissance",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["arts", "painting", "renaissance"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_052',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which English playwright authored 'Hamlet', 'Macbeth', 'Othello', and 'King Lear'?",
      back: "William Shakespeare (1564\u20131616, 'The Bard of Avon').",
      hint: "Associated with the Globe Theatre in London",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "theatre"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_053',
      groupId: 'grp_gk_u3',
      type: 'cloze',
      front: "Origins of Gothic Science Fiction",
      back: "Often considered the first true science fiction novel.",
      hint: '',
      clozeText: "Mary Shelley published her groundbreaking Gothic masterpiece {{c1::Frankenstein}} (subtitled The Modern Prometheus) in 1818 at age 20.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "novels"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_054',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which artistic movement derived its name from Claude Monet's 1872 painting 'Impression, Sunrise'?",
      back: "Impressionism.",
      hint: "Characterized by visible brush strokes, open composition, and changing qualities of light",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["arts", "art-history"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_055',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which foundational classical Greek philosopher was sentenced to death by drinking hemlock in 399 BCE?",
      back: "Socrates (teacher of Plato).",
      hint: "Known for his dialectic method of inquiry and 'The unexamined life is not worth living'",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["philosophy", "ancient-greece"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_056',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which German composer composed his monumental Ninth Symphony ('Ode to Joy') after losing his hearing?",
      back: "Ludwig van Beethoven (1770\u20131827).",
      hint: "Bridged the Classical and Romantic musical eras",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["music", "classical"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_057',
      groupId: 'grp_gk_u3',
      type: 'cloze',
      front: "Ancient Greek epics",
      back: "Composed in dactylic hexameter, recounting the Trojan War and Odysseus' ten-year homecoming journey.",
      hint: '',
      clozeText: "The seminal epic poems The Iliad and The Odyssey are traditionally attributed to the blind Greek poet {{c1::Homer}}.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "classics"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_058',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which Dutch Post-Impressionist painter created 'The Starry Night' while staying at Saint-R\u00e9my-de-Provence?",
      back: "Vincent van Gogh (1853\u20131890).",
      hint: "Fiercely supported by his brother Theo van Gogh",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["arts", "painting"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_059',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Who wrote the iconic 1845 narrative poem featuring a talking bird repeating 'Nevermore'?",
      back: "Edgar Allan Poe ('The Raven').",
      hint: "American master of the macabre and mystery genres",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "poetry"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_060',
      groupId: 'grp_gk_u3',
      type: 'reversible',
      front: "What does Ren\u00e9 Descartes' famous Latin philosophical statement 'Cogito, ergo sum' translate to?",
      back: "'I think, therefore I am.'",
      hint: "The fundamental element of Cartesian rationalism",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["philosophy", "latin"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_061',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which Spanish artist co-founded Cubism alongside Georges Braque and painted 'Guernica' in 1937?",
      back: "Pablo Picasso (1881\u20131973).",
      hint: "Went through Blue, Rose, and African-influenced stylistic periods",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["arts", "modern-art"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_062',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Who wrote the dystopian novel 'Nineteen Eighty-Four', introducing Big Brother, Thoughtcrime, and Newspeak?",
      back: "George Orwell (pen name of Eric Arthur Blair).",
      hint: "Also authored the satirical allegory 'Animal Farm'",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "dystopia"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_063',
      groupId: 'grp_gk_u3',
      type: 'cloze',
      front: "Vatican Renaissance masterpiece",
      back: "Commissioned by Pope Julius II; includes the celebrated panel 'The Creation of Adam'.",
      hint: '',
      clozeText: "Between 1508 and 1512, {{c1::Michelangelo}} painted the ceiling of the {{c2::Sistine Chapel}} in Rome.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["arts", "renaissance"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_064',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "What traditional Japanese poetic form consists of three phrases with a 5, 7, 5 mora/syllable structure?",
      back: "Haiku (often featuring a kigo or seasonal reference).",
      hint: "Masters include Matsuo Bash\u014d and Yosa Buson",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "poetry", "japan"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_065',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which Florentine sculptor created the iconic 17-foot marble statue of biblical hero David (1501\u20131504)?",
      back: "Michelangelo Buonarroti.",
      hint: "Currently housed at the Galleria dell'Accademia in Florence",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["arts", "sculpture"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_066',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which 19th-century Russian author wrote the epic novels 'War and Peace' and 'Anna Karenina'?",
      back: "Leo Tolstoy (1828\u20131910).",
      hint: "A master of realistic fiction and nonviolent resistance philosophy",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "russian"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_067',
      groupId: 'grp_gk_u3',
      type: 'reversible',
      front: "How many total keys (black and white combined) are on a standard modern acoustic piano?",
      back: "88 keys (52 white natural keys and 36 black accidental keys; 7 octaves plus a minor third).",
      hint: "Invented by Bartolomeo Cristofori in Italy around 1700",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["music", "instruments"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_068',
      groupId: 'grp_gk_u3',
      type: 'cloze',
      front: "Dante's spiritual journey",
      back: "Written in terza rima; guided through Hell by the Roman poet Virgil.",
      hint: '',
      clozeText: "Dante Alighieri's Italian narrative masterpiece The {{c1::Divine Comedy}} depicts the soul's journey through Inferno, Purgatorio, and {{c2::Paradiso}}.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "classics"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_069',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Who wrote the 1925 Jazz Age novel 'The Great Gatsby', narrated by Nick Carraway?",
      back: "F. Scott Fitzgerald.",
      hint: "Centers on the mysterious millionaire Jay Gatsby and his obsession with Daisy Buchanan",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "american"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_070',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which Dutch Golden Age painter created 'Girl with a Pearl Earring' (~1665)?",
      back: "Johannes Vermeer of Delft.",
      hint: "Renowned for his masterful use of light and the expensive pigment ultramarine",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["arts", "painting"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_071',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which ancient Sanskrit epic contains the 700-verse philosophical dialogue 'Bhagavad Gita'?",
      back: "The Mahabharata (traditionally attributed to sage Vyasa).",
      hint: "One of the two major Sanskrit epics of ancient India alongside the Ramayana",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "philosophy", "india"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_072',
      groupId: 'grp_gk_u3',
      type: 'reversible',
      front: "In musical notation, what Italian term indicates notes should be played smoothly and connected?",
      back: "Legato (indicated by a curved slur line over notes; opposite of staccato).",
      hint: "Literally means 'tied together' in Italian",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["music", "theory"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_073',
      groupId: 'grp_gk_u3',
      type: 'cloze',
      front: "Nietzschean concepts",
      back: "Challenged traditional morality and coined the aphorism 'God is dead'.",
      hint: '',
      clozeText: "German philosopher Friedrich Nietzsche introduced the concept of the \u00dcbermensch and the 'will to power' in his philosophical novel Thus Spoke {{c1::Zarathustra}}.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["philosophy"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_074',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Which acclaimed 20th-century Mexican artist is renowned for vivid, surreal self-portraits exploring identity and pain?",
      back: "Frida Kahlo (1907\u20131954).",
      hint: "Married to prominent Mexican muralist Diego Rivera",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["arts", "mexico"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_075',
      groupId: 'grp_gk_u3',
      type: 'basic',
      front: "Who authored the epic high-fantasy legendarium 'The Lord of the Rings' and 'The Hobbit'?",
      back: "J.R.R. Tolkien (John Ronald Reuel Tolkien, Oxford philologist).",
      hint: "Created extensive constructed languages including Elvish (Quenya and Sindarin)",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["literature", "fantasy"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_076',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "What was the first artificial Earth satellite, launched into orbit by the Soviet Union in October 1957?",
      back: "Sputnik 1.",
      hint: "Triggered the Space Race during the Cold War",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "history"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_077',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "Who was the first human to set foot on the lunar surface during Apollo 11 on July 20, 1969?",
      back: "Neil Armstrong ('That's one small step for man, one giant leap for mankind').",
      hint: "Followed moments later by lunar module pilot Buzz Aldrin",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "history"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_078',
      groupId: 'grp_gk_u4',
      type: 'cloze',
      front: "Invention of the Web",
      back: "Developed the first web browser, HTTP protocol, HTML language, and URI specifications.",
      hint: '',
      clozeText: "The World Wide Web (WWW) was invented by British scientist {{c1::Tim Berners-Lee}} in {{c2::1989}} while working at CERN.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "internet"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_079',
      groupId: 'grp_gk_u4',
      type: 'reversible',
      front: "In computer systems architecture, what does the abbreviation CPU stand for?",
      back: "Central Processing Unit (often called the 'brain' of the computer).",
      hint: "Executes machine instructions consisting of arithmetic, logic, and I/O operations",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "computing"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_080',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "What is the theoretical boundary around a black hole beyond which nothing, not even light, can escape?",
      back: "The Event Horizon (the radius of which is the Schwarzschild radius).",
      hint: "The point of no return",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "astrophysics"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_081',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "Which high-level programming language released in 1991 by Guido van Rossum was named after a British comedy troupe?",
      back: "Python (named after BBC's 'Monty Python's Flying Circus').",
      hint: "Known for clean syntax emphasizing code readability through indentation",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "programming"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_082',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "Which planet in our Solar System possesses the most prominent, extensive planetary ring system?",
      back: "Saturn (rings composed mostly of water ice particles and rocky debris).",
      hint: "The sixth planet from the Sun",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "planets"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_083',
      groupId: 'grp_gk_u4',
      type: 'cloze',
      front: "Digital data units",
      back: "Capable of representing 256 distinct binary values (from 0 to 255).",
      hint: '',
      clozeText: "In modern digital computing, 1 Byte is standardized to consist of exactly {{c1::8}} bits.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "computing"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_084',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "What is the name of our home barred spiral galaxy, containing an estimated 100 to 400 billion stars?",
      back: "The Milky Way.",
      hint: "Contains a supermassive black hole at its core known as Sagittarius A*",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "astronomy"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_085',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "In what year did Steve Jobs unveil the original Apple iPhone, fundamentally transforming mobile technology?",
      back: "2007 (announced January 9, released June 29).",
      hint: "Combined a widescreen iPod with touch controls, a mobile phone, and an internet communicator",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "smartphones"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_086',
      groupId: 'grp_gk_u4',
      type: 'reversible',
      front: "In computer hardware, what does RAM stand for?",
      back: "Random Access Memory (volatile primary memory used for fast data access).",
      hint: "Contrasts with non-volatile secondary storage like SSDs or HDDs",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "hardware"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_087',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "According to the Lambda-CDM model of Big Bang cosmology, what is the estimated age of the Universe?",
      back: "Approximately 13.8 billion years (13.787 \u00b1 0.020 billion years).",
      hint: "Derived from observations of the cosmic microwave background (CMB) by the Planck satellite",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "cosmology"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_088',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "Who is widely celebrated as the world's first computer programmer for writing an algorithm for Babbage's Analytical Engine in 1843?",
      back: "Ada Lovelace (Augusta Ada King, Countess of Lovelace; daughter of Lord Byron).",
      hint: "Envisioned that computing machines could manipulate symbols beyond mere numbers",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "history", "computing"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_089',
      groupId: 'grp_gk_u4',
      type: 'cloze',
      front: "Satellite navigation acronym",
      back: "Operated by the United States Space Force; uses trilateration from a constellation of 24+ satellites.",
      hint: '',
      clozeText: "The global satellite-based radio navigation network GPS stands for {{c1::Global Positioning System}}.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "navigation"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_090',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "Which NASA/ESA space telescope deployed into low Earth orbit in 1990 provided deep views of the cosmos?",
      back: "Hubble Space Telescope (HST).",
      hint: "Named after astronomer Edwin Hubble; complemented in 2021 by the James Webb Space Telescope",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "astronomy"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_091',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "Which planet in our Solar System has the highest average surface temperature due to a runaway greenhouse atmosphere?",
      back: "Venus (mean surface temperature around 465\u00b0C / 869\u00b0F).",
      hint: "Even hotter than Mercury despite being twice as far from the Sun",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "planets"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_092',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "What packet-switching research network funded by the US Department of Defense in 1969 was the precursor to the Internet?",
      back: "ARPANET (Advanced Research Projects Agency Network).",
      hint: "Pioneered TCP/IP and decentralized packet communications",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "internet"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_093',
      groupId: 'grp_gk_u4',
      type: 'cloze',
      front: "Einstein's Nobel achievement",
      back: "Demonstrated that light is absorbed and emitted in discrete energy quanta called photons.",
      hint: '',
      clozeText: "Albert Einstein was awarded the 1921 Nobel Prize in Physics specifically for his explanation of the {{c1::photoelectric effect}}, not for the theory of relativity.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["science", "physics", "nobel"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_094',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "What is the largest planet in our Solar System, with more mass than all other planets combined?",
      back: "Jupiter (a gas giant featuring the Great Red Spot storm).",
      hint: "Has dozens of moons including Io, Europa, Ganymede, and Callisto",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "planets"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_095',
      groupId: 'grp_gk_u4',
      type: 'reversible',
      front: "In web terminology, what does URL stand for?",
      back: "Uniform Resource Locator (a specific character string used to reference web resources).",
      hint: "The web address entered in browser navigation bars",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "internet"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_096',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "What astronomical event occurs when a massive star exhausts its nuclear fuel and undergoes a catastrophic gravitational collapse?",
      back: "A Supernova (leaving behind a neutron star, pulsar, or black hole).",
      hint: "Can briefly outshine an entire galaxy",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "astrophysics"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_097',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "Which Renaissance astronomer published 'De revolutionibus orbium coelestium' in 1543, proposing the heliocentric universe?",
      back: "Nicolaus Copernicus.",
      hint: "Displaced Ptolemy's geocentric model by placing the Sun near the center",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "history", "astronomy"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_098',
      groupId: 'grp_gk_u4',
      type: 'cloze',
      front: "Orbital period of the ISS",
      back: "Astronauts aboard experience approximately 16 sunrises and sunsets every 24 hours.",
      hint: '',
      clozeText: "The International Space Station (ISS) orbits Earth in low Earth orbit at ~28,000 km/h, completing an orbit roughly every {{c1::90}} minutes.",
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "iss"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_099',
      groupId: 'grp_gk_u4',
      type: 'reversible',
      front: "What does the hardware connection standard USB stand for?",
      back: "Universal Serial Bus (developed to standardize connection of computer peripherals).",
      hint: "Introduced in 1996; common iterations include Type-A and reversible Type-C",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["technology", "hardware"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    },
    {
      id: 'card_gk_100',
      groupId: 'grp_gk_u4',
      type: 'basic',
      front: "What is the name of NASA's car-sized Mars rover that landed in Jezero Crater in February 2021?",
      back: "Perseverance (nicknamed 'Percy', accompanied by the Ingenuity helicopter).",
      hint: "Tasked with seeking signs of ancient astrobiological life and caching rock core samples",
      clozeText: '',
      clozeMode: 'hide_all_guess_one',
      clozeSrs: {},
      imageUrl: '',
      imageOcclusions: [],
      occlusionMode: 'hide_all_guess_one',
      boxSrs: {},
      tags: ["space", "mars", "robotics"],
      srs: {
        state: 'new',
        interval: 0,
        easeFactor: 2.5,
        reps: 0,
        lapses: 0,
        dueDate: today,
        lastReviewed: null
      },
      createdAt: now,
      updatedAt: now
    }
  ];

  return { gkGroups, gkCards };
}
