/**
 * StudyCards Importers Engine
 * Parses and converts flashcard exports from:
 * - Quizlet (Text, TSV, CSV)
 * - Anki (Notes in Plain Text .txt/.tsv/.csv with HTML & Cloze syntax)
 * - RemNote (Markdown / Text .md/.txt with '::', ':::', ';;', '{{cloze}}')
 * - Brainscape (CSV export)
 * - Cram.com (TSV, CSV)
 * - Knowt (Quizlet text, CSV, JSON)
 * - Universal Delimited (CSV, TSV, Semicolon, Custom)
 * - StudyCards native JSON
 */

import { CARD_TYPES, generateId } from './models.js';

/**
 * Service metadata and instructional guides for users
 */
export const IMPORT_SERVICES = {
  auto: {
    id: 'auto',
    name: 'Auto-Detect',
    icon: '⚡',
    description: 'Automatically detects the format from file content or extension.',
    acceptedExts: '.txt,.tsv,.csv,.json,.md,.tab'
  },
  quizlet: {
    id: 'quizlet',
    name: 'Quizlet',
    icon: '🔵',
    description: 'Supports Quizlet text, TSV, and CSV exports.',
    instructions: 'In Quizlet, open your set, click the "..." menu ➔ "Export", then copy the text or download the file.',
    acceptedExts: '.txt,.tsv,.csv'
  },
  anki: {
    id: 'anki',
    name: 'Anki',
    icon: '🟢',
    description: 'Supports Anki Notes in Plain Text (.txt, .tsv) with HTML formatting and Cloze deletions.',
    instructions: 'In Anki, click File ➔ Export ➔ choose "Notes in Plain Text (*.txt)" and ensure "Include HTML" is checked.',
    acceptedExts: '.txt,.tsv,.csv'
  },
  remnote: {
    id: 'remnote',
    name: 'RemNote',
    icon: '🟣',
    description: 'Supports RemNote Markdown and Text exports with ::, :::, ;; and cloze {{...}} syntax.',
    instructions: 'In RemNote, click the document menu (...) ➔ Export ➔ choose "Markdown" or "Text".',
    acceptedExts: '.md,.txt'
  },
  brainscape: {
    id: 'brainscape',
    name: 'Brainscape',
    icon: '🟠',
    description: 'Supports Brainscape CSV exports (Question, Answer, Tags).',
    instructions: 'In Brainscape, open your deck, click the deck settings/menu ➔ "Export Deck" to CSV.',
    acceptedExts: '.csv'
  },
  cram: {
    id: 'cram',
    name: 'Cram.com',
    icon: '🟡',
    description: 'Supports Cram.com Tab-delimited (.txt) and CSV exports with optional hints.',
    instructions: 'On Cram.com, view your set ➔ click "Export" ➔ choose "Tab Delimited" or "Comma Delimited".',
    acceptedExts: '.txt,.tsv,.csv'
  },
  knowt: {
    id: 'knowt',
    name: 'Knowt',
    icon: '🔴',
    description: 'Supports Knowt Quizlet-formatted text, CSV, and JSON exports.',
    instructions: 'In Knowt, open your set ➔ click the "..." menu ➔ "Export" (Quizlet format, CSV, or JSON).',
    acceptedExts: '.txt,.csv,.json'
  },
  delimited: {
    id: 'delimited',
    name: 'Universal CSV / TSV',
    icon: '📄',
    description: 'Any spreadsheet or text file separated by commas, tabs, semicolons, or pipes.',
    instructions: 'Export your spreadsheet as CSV or TSV, or paste text with a consistent separator between Question and Answer.',
    acceptedExts: '.csv,.tsv,.txt'
  },
  studycards: {
    id: 'studycards',
    name: 'StudyCards Backup',
    icon: '🎴',
    description: 'Native StudyCards backup file containing folders, card types, and study settings.',
    instructions: 'Select a .json backup file generated by StudyCards "Backup & Share".',
    acceptedExts: '.json'
  }
};

/**
 * Robust RFC-4180 CSV / TSV Parser
 * Correctly handles quotes, escaped quotes (""), newlines inside quotes, and custom delimiters.
 */
export function parseDelimitedRows(text, delimiter = null) {
  if (!text) return [];

  // Strip UTF-8 BOM if present
  let cleanText = text.replace(/^\uFEFF/, '').trim();

  // Strip Anki comment lines at start (e.g. #separator:tab, #html:true, #tags column:3)
  const lines = cleanText.split(/\r?\n/);
  const contentLines = [];
  let ankiDetectedSep = null;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('#separator:')) {
      const sepName = trimmed.replace('#separator:', '').trim().toLowerCase();
      if (sepName === 'tab' || sepName === '\\t') ankiDetectedSep = '\t';
      else if (sepName === 'comma' || sepName === ',') ankiDetectedSep = ',';
      else if (sepName === 'semicolon' || sepName === ';') ankiDetectedSep = ';';
    } else if (trimmed.startsWith('#')) {
      // skip other comment headers
      continue;
    } else {
      contentLines.push(line);
    }
  }

  cleanText = contentLines.join('\n');
  if (!cleanText.trim()) return [];

  // Auto-detect delimiter if not forced
  if (!delimiter) {
    if (ankiDetectedSep) {
      delimiter = ankiDetectedSep;
    } else {
      // Count delimiters in first few lines
      const sample = cleanText.split('\n').slice(0, 5).join('\n');
      const tabCount = (sample.match(/\t/g) || []).length;
      const commaCount = (sample.match(/,/g) || []).length;
      const semiCount = (sample.match(/;/g) || []).length;
      const pipeCount = (sample.match(/\|/g) || []).length;

      if (tabCount >= 2 && tabCount >= commaCount) delimiter = '\t';
      else if (commaCount >= 2) delimiter = ',';
      else if (semiCount >= 2) delimiter = ';';
      else if (pipeCount >= 2) delimiter = '|';
      else delimiter = '\t'; // default to tab
    }
  }

  // Tokenize rows and fields
  const rows = [];
  let currentRow = [];
  let currentField = '';
  let inQuotes = false;
  let i = 0;
  const len = cleanText.length;

  while (i < len) {
    const char = cleanText[i];
    const nextChar = i + 1 < len ? cleanText[i + 1] : '';

    if (inQuotes) {
      if (char === '"' && nextChar === '"') {
        currentField += '"';
        i += 2;
        continue;
      } else if (char === '"') {
        inQuotes = false;
        i++;
        continue;
      } else {
        currentField += char;
        i++;
        continue;
      }
    } else {
      if (char === '"') {
        inQuotes = true;
        i++;
        continue;
      } else if (char === delimiter) {
        currentRow.push(currentField);
        currentField = '';
        i++;
        continue;
      } else if (char === '\r' && nextChar === '\n') {
        currentRow.push(currentField);
        rows.push(currentRow);
        currentRow = [];
        currentField = '';
        i += 2;
        continue;
      } else if (char === '\n' || char === '\r') {
        currentRow.push(currentField);
        rows.push(currentRow);
        currentRow = [];
        currentField = '';
        i++;
        continue;
      } else {
        currentField += char;
        i++;
        continue;
      }
    }
  }

  if (currentField.length > 0 || currentRow.length > 0) {
    currentRow.push(currentField);
    rows.push(currentRow);
  }

  return rows;
}

/**
 * Clean & normalize HTML from Anki or web exports
 */
function cleanHtml(html) {
  if (!html) return '';
  let text = html
    .replace(/<br\s*[\/]?>/gi, '\n')
    .replace(/<\/div>/gi, '\n')
    .replace(/<div>/gi, '')
    .replace(/<\/p>/gi, '\n\n')
    .replace(/<p>/gi, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");

  // Keep clean inline tags like <b>, <i>, <code>, <u>, <em>, <strong>
  // Strip dangerous or layout tags
  text = text.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '');
  text = text.replace(/<style\b[^<]*(?:(?!<\/style>)<[^<]*)*<\/style>/gi, '');
  return text.trim();
}

/**
 * Detect Cloze deletion syntax (e.g. {{c1::answer}} or {{answer}})
 */
function detectCloze(text) {
  if (!text) return null;
  // Anki-style {{c1::answer}} or {{c1::answer::hint}}
  if (/\{\{c\d+::.*?\}\}/i.test(text)) {
    return text;
  }
  // RemNote or simple cloze {{answer}}
  if (/\{\{[^{}]+?\}\}/.test(text)) {
    let clozeIdx = 1;
    // Normalize simple {{answer}} to {{c1::answer}}
    return text.replace(/\{\{([^{}]+?)\}\}/g, (_, match) => {
      if (match.startsWith('c') && match.includes('::')) return `{{${match}}}`;
      const res = `{{c${clozeIdx}::${match}}}`;
      clozeIdx++;
      return res;
    });
  }
  return null;
}

/**
 * Auto-detect the likely service based on filename and text content
 */
export function autoDetectService(text, filename = '') {
  const ext = filename ? filename.toLowerCase().split('.').pop() : '';
  const trimmed = text.trim();

  // 1. JSON
  if (ext === 'json' || (trimmed.startsWith('{') && trimmed.endsWith('}'))) {
    try {
      const parsed = JSON.parse(trimmed);
      if (parsed.cards && parsed.groups) return 'studycards';
      if (Array.isArray(parsed) || parsed.cards || parsed.terms) return 'knowt';
    } catch (e) {
      // not valid JSON
    }
  }

  // 2. Anki Comments
  if (trimmed.startsWith('#separator:') || trimmed.startsWith('#html:') || trimmed.startsWith('#tags column:')) {
    return 'anki';
  }

  // 3. RemNote (Markdown with :: or ::: or ;;)
  if (ext === 'md' || /(?:^|\n).+?\s*:::\s*.+/m.test(trimmed) || /(?:^|\n).+?\s*::\s*.+/m.test(trimmed) || /(?:^|\n).+?\s*;;/m.test(trimmed)) {
    return 'remnote';
  }

  // 4. Brainscape CSV header
  if (ext === 'csv' || /^["']?Question["']?\s*,\s*["']?Answer["']?/i.test(trimmed)) {
    return 'brainscape';
  }

  // 5. Quizlet or Universal TSV
  if (ext === 'tsv' || (trimmed.split('\n').length > 1 && trimmed.includes('\t'))) {
    return 'quizlet';
  }

  if (ext === 'csv') {
    return 'delimited';
  }

  return 'quizlet';
}

/**
 * Main parse dispatcher
 */
export function parseImport(rawText, serviceId = 'auto', options = {}) {
  const filename = typeof options === 'string' ? options : (options?.fileName || '');
  let activeService = serviceId;
  if (!activeService || activeService === 'auto') {
    activeService = autoDetectService(rawText, filename);
  }

  let result = null;

  switch (activeService) {
    case 'studycards':
      result = parseStudyCardsJson(rawText);
      break;
    case 'quizlet':
      result = parseQuizlet(rawText);
      break;
    case 'anki':
      result = parseAnki(rawText);
      break;
    case 'remnote':
      result = parseRemNote(rawText);
      break;
    case 'brainscape':
      result = parseBrainscape(rawText);
      break;
    case 'cram':
      result = parseCram(rawText);
      break;
    case 'knowt':
      result = parseKnowt(rawText);
      break;
    case 'delimited':
    default:
      result = parseDelimited(rawText);
      break;
  }

  // Suggest deck name from filename or options if available
  if (options && options.deckName && (!result.deckName || result.deckName.includes('Deck'))) {
    result.deckName = options.deckName;
  } else if (filename) {
    const baseName = filename.split(/[\\/]/).pop() || filename;
    const cleanName = baseName.replace(/\.[^/.]+$/, '').replace(/[_-]/g, ' ').trim();
    if (cleanName && (!result.deckName || result.deckName === 'Imported Deck')) {
      result.deckName = cleanName.charAt(0).toUpperCase() + cleanName.slice(1);
    }
  }

  return result;
}

export const parseImportData = (rawText, serviceId = 'auto', filename = '') =>
  parseImport(rawText, serviceId, { fileName: filename });

/**
 * 1. Parse Quizlet Export
 */
export function parseQuizlet(text) {
  const rows = parseDelimitedRows(text);
  const cards = [];
  const warnings = [];
  let lineNum = 0;

  for (const row of rows) {
    lineNum++;
    if (!row || row.length === 0 || (row.length === 1 && !row[0].trim())) {
      continue; // empty line
    }

    const front = (row[0] || '').trim();
    const back = (row.slice(1).join('\t') || '').trim();

    if (!front && !back) continue;

    if (!front) {
      warnings.push({ line: lineNum, reason: 'Missing term/question (front is empty)', rawSnippet: back.substring(0, 40) });
      continue;
    }
    if (!back) {
      warnings.push({ line: lineNum, reason: 'Missing definition/answer (back is empty)', rawSnippet: front.substring(0, 40) });
      continue;
    }

    cards.push({
      front: cleanHtml(front),
      back: cleanHtml(back),
      hint: '',
      tags: ['quizlet'],
      type: CARD_TYPES.BASIC,
      clozeText: '',
      sourceLine: lineNum
    });
  }

  return buildResult('Quizlet', cards, warnings, rows.length);
}

/**
 * 2. Parse Anki Plain Text / Notes
 */
export function parseAnki(text) {
  const rows = parseDelimitedRows(text, '\t');
  const cards = [];
  const warnings = [];
  let lineNum = 0;

  for (const row of rows) {
    lineNum++;
    if (!row || row.length === 0 || (row.length === 1 && !row[0].trim())) {
      continue;
    }

    const field1 = (row[0] || '').trim();
    const field2 = row.length > 1 ? (row[1] || '').trim() : '';
    const field3 = row.length > 2 ? (row[2] || '').trim() : '';

    if (!field1 && !field2) continue;

    // Check for Anki Cloze in field 1
    const clozeField1 = detectCloze(field1);
    if (clozeField1) {
      cards.push({
        front: cleanHtml(field1.replace(/\{\{c\d+::(.*?)(?:::.*?)?\}\}/gi, '[...]')),
        back: cleanHtml(field2 || field1),
        hint: '',
        tags: field3 ? field3.split(/\s+/).filter(Boolean) : ['anki'],
        type: CARD_TYPES.CLOZE,
        clozeText: clozeField1,
        sourceLine: lineNum
      });
      continue;
    }

    // Standard Basic Anki card
    if (!field1) {
      warnings.push({ line: lineNum, reason: 'Missing question (Front is empty)', rawSnippet: field2.substring(0, 40) });
      continue;
    }
    if (!field2) {
      warnings.push({ line: lineNum, reason: 'Missing answer (Back is empty)', rawSnippet: field1.substring(0, 40) });
      continue;
    }

    cards.push({
      front: cleanHtml(field1),
      back: cleanHtml(field2),
      hint: '',
      tags: field3 ? field3.split(/\s+/).filter(Boolean) : ['anki'],
      type: CARD_TYPES.BASIC,
      clozeText: '',
      sourceLine: lineNum
    });
  }

  return buildResult('Anki', cards, warnings, rows.length);
}

/**
 * 3. Parse RemNote Markdown / Text
 */
export function parseRemNote(text) {
  const lines = text.split(/\r?\n/);
  const cards = [];
  const warnings = [];
  let lineNum = 0;

  let multilineQuestion = null;
  let multilineBuffer = [];
  let multilineStart = 0;

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    lineNum = i + 1;
    const line = rawLine.trim();

    if (!line) continue;

    // Handle multiline continuation (after ';;')
    if (multilineQuestion !== null) {
      if (line.includes('::') || line.endsWith(';;')) {
        // End multiline and process previous
        if (multilineBuffer.length > 0) {
          cards.push({
            front: cleanHtml(multilineQuestion),
            back: cleanHtml(multilineBuffer.join('\n')),
            hint: '',
            tags: ['remnote'],
            type: CARD_TYPES.BASIC,
            clozeText: '',
            sourceLine: multilineStart
          });
        }
        multilineQuestion = null;
        multilineBuffer = [];
      } else {
        multilineBuffer.push(line);
        continue;
      }
    }

    // Multiline trigger (ends with ';;')
    if (line.endsWith(';;') && !line.includes('::')) {
      multilineQuestion = line.replace(/;;$/, '').trim();
      multilineStart = lineNum;
      multilineBuffer = [];
      continue;
    }

    // Bidirectional / Reversible card: Concept ::: Definition
    if (line.includes(':::')) {
      const parts = line.split(':::');
      const front = parts[0].replace(/^[-*•]\s*/, '').trim();
      const back = parts.slice(1).join(':::').trim();
      if (front && back) {
        cards.push({
          front: cleanHtml(front),
          back: cleanHtml(back),
          hint: '',
          tags: ['remnote'],
          type: CARD_TYPES.REVERSIBLE,
          clozeText: '',
          sourceLine: lineNum
        });
      } else {
        warnings.push({ line: lineNum, reason: 'Incomplete reversible card (missing front or back)', rawSnippet: line.substring(0, 40) });
      }
      continue;
    }

    // Standard card: Concept :: Definition
    if (line.includes('::')) {
      const parts = line.split('::');
      const front = parts[0].replace(/^[-*•]\s*/, '').trim();
      const back = parts.slice(1).join('::').trim();
      if (front && back) {
        cards.push({
          front: cleanHtml(front),
          back: cleanHtml(back),
          hint: '',
          tags: ['remnote'],
          type: CARD_TYPES.BASIC,
          clozeText: '',
          sourceLine: lineNum
        });
      } else {
        warnings.push({ line: lineNum, reason: 'Incomplete card (missing front or back)', rawSnippet: line.substring(0, 40) });
      }
      continue;
    }

    // RemNote Cloze: text with {{concept}}
    const cloze = detectCloze(line);
    if (cloze) {
      cards.push({
        front: cleanHtml(line.replace(/\{\{([^{}]+?)\}\}/g, '[...]').replace(/^[-*•]\s*/, '')),
        back: cleanHtml(line.replace(/^[-*•]\s*/, '')),
        hint: '',
        tags: ['remnote'],
        type: CARD_TYPES.CLOZE,
        clozeText: cloze.replace(/^[-*•]\s*/, ''),
        sourceLine: lineNum
      });
      continue;
    }
  }

  // Flush trailing multiline
  if (multilineQuestion && multilineBuffer.length > 0) {
    cards.push({
      front: cleanHtml(multilineQuestion),
      back: cleanHtml(multilineBuffer.join('\n')),
      hint: '',
      tags: ['remnote'],
      type: CARD_TYPES.BASIC,
      clozeText: '',
      sourceLine: multilineStart
    });
  }

  return buildResult('RemNote', cards, warnings, lines.length);
}

/**
 * 4. Parse Brainscape CSV
 */
export function parseBrainscape(text) {
  const rows = parseDelimitedRows(text, ',');
  const cards = [];
  const warnings = [];
  let lineNum = 0;

  let hasHeader = false;
  if (rows.length > 0) {
    const r0 = rows[0].map(c => c.toLowerCase().trim());
    if (r0.includes('question') && r0.includes('answer')) {
      hasHeader = true;
    }
  }

  const startIdx = hasHeader ? 1 : 0;

  for (let i = startIdx; i < rows.length; i++) {
    lineNum = i + 1;
    const row = rows[i];
    if (!row || row.length === 0 || (row.length === 1 && !row[0].trim())) continue;

    const front = (row[0] || '').trim();
    const back = (row[1] || '').trim();
    const tags = row.length > 2 ? [row[2].trim()] : ['brainscape'];

    if (!front && !back) continue;

    if (!front) {
      warnings.push({ line: lineNum, reason: 'Missing question', rawSnippet: back.substring(0, 40) });
      continue;
    }
    if (!back) {
      warnings.push({ line: lineNum, reason: 'Missing answer', rawSnippet: front.substring(0, 40) });
      continue;
    }

    cards.push({
      front: cleanHtml(front),
      back: cleanHtml(back),
      hint: '',
      tags: tags.filter(Boolean),
      type: CARD_TYPES.BASIC,
      clozeText: '',
      sourceLine: lineNum
    });
  }

  return buildResult('Brainscape', cards, warnings, rows.length);
}

/**
 * 5. Parse Cram.com Export (TSV or CSV with optional hint)
 */
export function parseCram(text) {
  const rows = parseDelimitedRows(text);
  const cards = [];
  const warnings = [];
  let lineNum = 0;

  for (const row of rows) {
    lineNum++;
    if (!row || row.length === 0 || (row.length === 1 && !row[0].trim())) continue;

    const front = (row[0] || '').trim();
    const back = (row[1] || '').trim();
    const hint = row.length > 2 ? (row[2] || '').trim() : '';

    if (!front && !back) continue;

    if (!front) {
      warnings.push({ line: lineNum, reason: 'Missing front side', rawSnippet: back.substring(0, 40) });
      continue;
    }
    if (!back) {
      warnings.push({ line: lineNum, reason: 'Missing back side', rawSnippet: front.substring(0, 40) });
      continue;
    }

    cards.push({
      front: cleanHtml(front),
      back: cleanHtml(back),
      hint: cleanHtml(hint),
      tags: ['cram'],
      type: CARD_TYPES.BASIC,
      clozeText: '',
      sourceLine: lineNum
    });
  }

  return buildResult('Cram.com', cards, warnings, rows.length);
}

/**
 * 6. Parse Knowt Export (Quizlet text, CSV, or Knowt JSON)
 */
export function parseKnowt(text) {
  const trimmed = text.trim();
  // Check if JSON
  if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
    try {
      const data = JSON.parse(trimmed);
      const items = Array.isArray(data) ? data : (data.cards || data.terms || data.flashcards || []);
      const cards = [];
      const warnings = [];
      let idx = 0;

      for (const item of items) {
        idx++;
        const front = (item.term || item.front || item.question || '').trim();
        const back = (item.definition || item.back || item.answer || '').trim();

        if (!front && !back) continue;
        if (!front) {
          warnings.push({ line: idx, reason: 'Missing term/front', rawSnippet: back.substring(0, 40) });
          continue;
        }
        if (!back) {
          warnings.push({ line: idx, reason: 'Missing definition/back', rawSnippet: front.substring(0, 40) });
          continue;
        }

        cards.push({
          front: cleanHtml(front),
          back: cleanHtml(back),
          hint: (item.hint || '').trim(),
          tags: ['knowt'],
          type: CARD_TYPES.BASIC,
          clozeText: '',
          sourceLine: idx
        });
      }
      return buildResult('Knowt', cards, warnings, items.length);
    } catch (e) {
      // Fall through to delimited parsing
    }
  }

  // Otherwise Quizlet-style text or CSV
  return parseQuizlet(text);
}

/**
 * 7. Universal Delimited Parser (CSV, TSV, Semicolon, Custom)
 */
export function parseDelimited(text, customDelimiter = null) {
  const rows = parseDelimitedRows(text, customDelimiter);
  const cards = [];
  const warnings = [];
  let lineNum = 0;

  // Header detection (check for "Front", "Question", "Term")
  let startIdx = 0;
  if (rows.length > 0) {
    const r0 = rows[0].map(c => c.toLowerCase().trim());
    if (
      (r0.includes('front') || r0.includes('question') || r0.includes('term')) &&
      (r0.includes('back') || r0.includes('answer') || r0.includes('definition'))
    ) {
      startIdx = 1;
    }
  }

  for (let i = startIdx; i < rows.length; i++) {
    lineNum = i + 1;
    const row = rows[i];
    if (!row || row.length === 0 || (row.length === 1 && !row[0].trim())) continue;

    const front = (row[0] || '').trim();
    const back = (row.slice(1).join(' ') || '').trim();

    if (!front && !back) continue;

    if (!front) {
      warnings.push({ line: lineNum, reason: 'Column 1 is empty', rawSnippet: back.substring(0, 40) });
      continue;
    }
    if (!back) {
      warnings.push({ line: lineNum, reason: 'Column 2 (Answer) is empty', rawSnippet: front.substring(0, 40) });
      continue;
    }

    // Check for cloze in front
    const cloze = detectCloze(front);

    cards.push({
      front: cleanHtml(front),
      back: cleanHtml(back),
      hint: '',
      tags: ['imported'],
      type: cloze ? CARD_TYPES.CLOZE : CARD_TYPES.BASIC,
      clozeText: cloze || '',
      sourceLine: lineNum
    });
  }

  return buildResult('Delimited File', cards, warnings, rows.length);
}

/**
 * 8. StudyCards Native JSON Backup
 */
export function parseStudyCardsJson(jsonString) {
  try {
    const data = JSON.parse(jsonString);
    if (!data || !Array.isArray(data.cards) || !Array.isArray(data.groups)) {
      return {
        success: false,
        serviceName: 'StudyCards Backup',
        error: 'Not a valid StudyCards backup file (missing cards or groups array).',
        cards: [],
        warnings: [{ line: 1, reason: 'Invalid JSON schema', rawSnippet: '' }],
        stats: { totalRows: 0, validCards: 0, skippedRows: 0, cardTypes: {} },
        isNativeBackup: true,
        nativeData: null
      };
    }

    const typeCounts = {};
    for (const c of data.cards) {
      typeCounts[c.type || 'basic'] = (typeCounts[c.type || 'basic'] || 0) + 1;
    }

    return {
      success: true,
      serviceName: 'StudyCards Backup',
      deckName: 'StudyCards Collection',
      cards: data.cards,
      groups: data.groups,
      settings: data.settings,
      warnings: [],
      stats: {
        totalRows: data.cards.length,
        validCards: data.cards.length,
        skippedRows: 0,
        cardTypes: typeCounts,
        groupsCount: data.groups.length
      },
      isNativeBackup: true,
      nativeData: data
    };
  } catch (err) {
    return {
      success: false,
      serviceName: 'StudyCards Backup',
      error: `JSON parse error: ${err.message}`,
      cards: [],
      warnings: [{ line: 1, reason: err.message, rawSnippet: '' }],
      stats: { totalRows: 0, validCards: 0, skippedRows: 1, cardTypes: {} },
      isNativeBackup: true,
      nativeData: null
    };
  }
}

/**
 * Construct standardized parse result object
 */
function buildResult(serviceName, cards, warnings, totalRows) {
  const typeCounts = { basic: 0, cloze: 0, reversible: 0 };
  for (const c of cards) {
    if (c.type === CARD_TYPES.CLOZE) typeCounts.cloze++;
    else if (c.type === CARD_TYPES.REVERSIBLE) typeCounts.reversible++;
    else typeCounts.basic++;
  }

  return {
    success: cards.length > 0,
    serviceName,
    deckName: `${serviceName} Deck`,
    cards,
    warnings,
    stats: {
      totalRows,
      validCards: cards.length,
      skippedRows: warnings.length,
      cardTypes: typeCounts
    },
    isNativeBackup: false,
    nativeData: null
  };
}
